// Auto-generated by scripts/organize-images.mjs
// Do not edit manually.

export interface Collection {
    landscape: string[]
    portrait: string[]
}

export interface Collections {
    default: Collection
    bnw: Collection
}

export const COLLECTIONS: Collections = {
    default: {
        landscape: [
    "/images/avif/color/landscape/LBwb-10.avif",
    "/images/avif/color/landscape/LBwb-100.avif",
    "/images/avif/color/landscape/LBwb-102.avif",
    "/images/avif/color/landscape/LBwb-103.avif",
    "/images/avif/color/landscape/LBwb-127.avif",
    "/images/avif/color/landscape/LBwb-143.avif",
    "/images/avif/color/landscape/LBwb-144.avif",
    "/images/avif/color/landscape/LBwb-149.avif",
    "/images/avif/color/landscape/LBwb-15.avif",
    "/images/avif/color/landscape/LBwb-150.avif",
    "/images/avif/color/landscape/LBwb-153.avif",
    "/images/avif/color/landscape/LBwb-16.avif",
    "/images/avif/color/landscape/LBwb-173.avif",
    "/images/avif/color/landscape/LBwb-175.avif",
    "/images/avif/color/landscape/LBwb-2.avif",
    "/images/avif/color/landscape/LBwb-29.avif",
    "/images/avif/color/landscape/LBwb-3.avif",
    "/images/avif/color/landscape/LBwb-32.avif",
    "/images/avif/color/landscape/LBwb-33.avif",
    "/images/avif/color/landscape/LBwb-36.avif",
    "/images/avif/color/landscape/LBwb-42.avif",
    "/images/avif/color/landscape/LBwb-5.avif",
    "/images/avif/color/landscape/LBwb-6.avif",
    "/images/avif/color/landscape/LBwb-62.avif",
    "/images/avif/color/landscape/LBwb-7.avif",
    "/images/avif/color/landscape/LBwb-70.avif",
    "/images/avif/color/landscape/LBwb-84.avif",
    "/images/avif/color/landscape/LBwb-85.avif",
    "/images/avif/color/landscape/LBwb-91.avif",
    "/images/avif/color/landscape/LBwb-92.avif",
    "/images/avif/color/landscape/LBwb-93.avif",
    "/images/avif/color/landscape/LBwb-94.avif",
    "/images/avif/color/landscape/LBwb-97.avif",
    "/images/avif/color/landscape/LBwb-98.avif"
],
        portrait: [
    "/images/avif/color/portrait/LBwb-101.avif",
    "/images/avif/color/portrait/LBwb-108.avif",
    "/images/avif/color/portrait/LBwb-109.avif",
    "/images/avif/color/portrait/LBwb-11.avif",
    "/images/avif/color/portrait/LBwb-110.avif",
    "/images/avif/color/portrait/LBwb-113.avif",
    "/images/avif/color/portrait/LBwb-115.avif",
    "/images/avif/color/portrait/LBwb-116.avif",
    "/images/avif/color/portrait/LBwb-117.avif",
    "/images/avif/color/portrait/LBwb-118.avif",
    "/images/avif/color/portrait/LBwb-119.avif",
    "/images/avif/color/portrait/LBwb-12.avif",
    "/images/avif/color/portrait/LBwb-121.avif",
    "/images/avif/color/portrait/LBwb-122.avif",
    "/images/avif/color/portrait/LBwb-124.avif",
    "/images/avif/color/portrait/LBwb-125.avif",
    "/images/avif/color/portrait/LBwb-126.avif",
    "/images/avif/color/portrait/LBwb-13.avif",
    "/images/avif/color/portrait/LBwb-131.avif",
    "/images/avif/color/portrait/LBwb-132.avif",
    "/images/avif/color/portrait/LBwb-134.avif",
    "/images/avif/color/portrait/LBwb-14.avif",
    "/images/avif/color/portrait/LBwb-140.avif",
    "/images/avif/color/portrait/LBwb-152.avif",
    "/images/avif/color/portrait/LBwb-154.avif",
    "/images/avif/color/portrait/LBwb-161.avif",
    "/images/avif/color/portrait/LBwb-162.avif",
    "/images/avif/color/portrait/LBwb-163.avif",
    "/images/avif/color/portrait/LBwb-164.avif",
    "/images/avif/color/portrait/LBwb-165.avif",
    "/images/avif/color/portrait/LBwb-168.avif",
    "/images/avif/color/portrait/LBwb-17.avif",
    "/images/avif/color/portrait/LBwb-170.avif",
    "/images/avif/color/portrait/LBwb-172.avif",
    "/images/avif/color/portrait/LBwb-174.avif",
    "/images/avif/color/portrait/LBwb-18.avif",
    "/images/avif/color/portrait/LBwb-22.avif",
    "/images/avif/color/portrait/LBwb-23.avif",
    "/images/avif/color/portrait/LBwb-24.avif",
    "/images/avif/color/portrait/LBwb-25.avif",
    "/images/avif/color/portrait/LBwb-26.avif",
    "/images/avif/color/portrait/LBwb-27.avif",
    "/images/avif/color/portrait/LBwb-28.avif",
    "/images/avif/color/portrait/LBwb-30.avif",
    "/images/avif/color/portrait/LBwb-31.avif",
    "/images/avif/color/portrait/LBwb-37.avif",
    "/images/avif/color/portrait/LBwb-39.avif",
    "/images/avif/color/portrait/LBwb-4.avif",
    "/images/avif/color/portrait/LBwb-40.avif",
    "/images/avif/color/portrait/LBwb-41.avif",
    "/images/avif/color/portrait/LBwb-44.avif",
    "/images/avif/color/portrait/LBwb-46.avif",
    "/images/avif/color/portrait/LBwb-48.avif",
    "/images/avif/color/portrait/LBwb-49.avif",
    "/images/avif/color/portrait/LBwb-50.avif",
    "/images/avif/color/portrait/LBwb-54.avif",
    "/images/avif/color/portrait/LBwb-55.avif",
    "/images/avif/color/portrait/LBwb-57.avif",
    "/images/avif/color/portrait/LBwb-58.avif",
    "/images/avif/color/portrait/LBwb-59.avif",
    "/images/avif/color/portrait/LBwb-60.avif",
    "/images/avif/color/portrait/LBwb-61.avif",
    "/images/avif/color/portrait/LBwb-63.avif",
    "/images/avif/color/portrait/LBwb-64.avif",
    "/images/avif/color/portrait/LBwb-65.avif",
    "/images/avif/color/portrait/LBwb-69.avif",
    "/images/avif/color/portrait/LBwb-73.avif",
    "/images/avif/color/portrait/LBwb-75.avif",
    "/images/avif/color/portrait/LBwb-76.avif",
    "/images/avif/color/portrait/LBwb-8.avif",
    "/images/avif/color/portrait/LBwb-86.avif",
    "/images/avif/color/portrait/LBwb-87.avif",
    "/images/avif/color/portrait/LBwb-90.avif",
    "/images/avif/color/portrait/LBwb-96.avif",
    "/images/avif/color/portrait/LBwb-99.avif",
    "/images/avif/color/portrait/LBwb.avif"
]
    },
    bnw: {
        landscape: [
    "/images/avif/bnw/landscape/LBwb-106.avif",
    "/images/avif/bnw/landscape/LBwb-146.avif",
    "/images/avif/bnw/landscape/LBwb-147.avif",
    "/images/avif/bnw/landscape/LBwb-35.avif",
    "/images/avif/bnw/landscape/LBwb-38.avif"
],
        portrait: [
    "/images/avif/bnw/portrait/LBwb-104.avif",
    "/images/avif/bnw/portrait/LBwb-107.avif",
    "/images/avif/bnw/portrait/LBwb-145.avif",
    "/images/avif/bnw/portrait/LBwb-148.avif",
    "/images/avif/bnw/portrait/LBwb-155.avif",
    "/images/avif/bnw/portrait/LBwb-156.avif",
    "/images/avif/bnw/portrait/LBwb-157.avif",
    "/images/avif/bnw/portrait/LBwb-158.avif",
    "/images/avif/bnw/portrait/LBwb-159.avif",
    "/images/avif/bnw/portrait/LBwb-160.avif",
    "/images/avif/bnw/portrait/LBwb-19.avif",
    "/images/avif/bnw/portrait/LBwb-20.avif",
    "/images/avif/bnw/portrait/LBwb-21.avif",
    "/images/avif/bnw/portrait/LBwb-52.avif",
    "/images/avif/bnw/portrait/LBwb-53.avif",
    "/images/avif/bnw/portrait/LBwb-77.avif",
    "/images/avif/bnw/portrait/LBwb-78.avif",
    "/images/avif/bnw/portrait/LBwb-79.avif",
    "/images/avif/bnw/portrait/LBwb-80.avif",
    "/images/avif/bnw/portrait/LBwb-81.avif",
    "/images/avif/bnw/portrait/LBwb-88.avif",
    "/images/avif/bnw/portrait/LBwb-89.avif"
]
    }
}

// Utility to shuffle array
export function shuffle<T>(array: T[]): T[] {
    const shuffled = [...array]
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
    }
    return shuffled
}
