// Collections data structure matching SITO config.js
export interface Collection {
    landscape: string[]
    portrait: string[]
}

export interface Collections {
    default: Collection
    bnw: Collection
}

export const COLLECTIONS: Collections = {
    default: {
        landscape: [
            "/images/avif/color/landscape/Mod-10.avif",
            "/images/avif/color/landscape/Mod-100.avif",
            "/images/avif/color/landscape/Mod-102.avif",
            "/images/avif/color/landscape/Mod-103.avif",
            "/images/avif/color/landscape/Mod-120.avif",
            "/images/avif/color/landscape/Mod-127.avif",
            "/images/avif/color/landscape/Mod-135.avif",
            "/images/avif/color/landscape/Mod-141.avif",
            "/images/avif/color/landscape/Mod-142.avif",
            "/images/avif/color/landscape/Mod-143.avif",
            "/images/avif/color/landscape/Mod-149.avif",
            "/images/avif/color/landscape/Mod-15.avif",
            "/images/avif/color/landscape/Mod-150.avif",
            "/images/avif/color/landscape/Mod-153.avif",
            "/images/avif/color/landscape/Mod-16.avif",
            "/images/avif/color/landscape/Mod-166.avif",
            "/images/avif/color/landscape/Mod-171.avif",
            "/images/avif/color/landscape/Mod-173.avif",
            "/images/avif/color/landscape/Mod-175.avif",
            "/images/avif/color/landscape/Mod-176.avif",
            "/images/avif/color/landscape/Mod-29.avif",
            "/images/avif/color/landscape/Mod-3.avif",
            "/images/avif/color/landscape/Mod-32.avif",
            "/images/avif/color/landscape/Mod-33.avif",
            "/images/avif/color/landscape/Mod-36.avif",
            "/images/avif/color/landscape/Mod-42.avif",
            "/images/avif/color/landscape/Mod-43.avif",
            "/images/avif/color/landscape/Mod-47.avif",
            "/images/avif/color/landscape/Mod-5.avif",
            "/images/avif/color/landscape/Mod-51.avif",
            "/images/avif/color/landscape/Mod-56.avif",
            "/images/avif/color/landscape/Mod-6.avif",
            "/images/avif/color/landscape/Mod-62.avif",
            "/images/avif/color/landscape/Mod-66.avif",
            "/images/avif/color/landscape/Mod-7.avif",
            "/images/avif/color/landscape/Mod-70.avif",
            "/images/avif/color/landscape/Mod-82.avif",
            "/images/avif/color/landscape/Mod-83.avif",
            "/images/avif/color/landscape/Mod-84.avif",
            "/images/avif/color/landscape/Mod-85.avif",
            "/images/avif/color/landscape/Mod-91.avif",
            "/images/avif/color/landscape/Mod-92.avif",
            "/images/avif/color/landscape/Mod-93.avif",
            "/images/avif/color/landscape/Mod-94.avif",
            "/images/avif/color/landscape/Mod-97.avif",
            "/images/avif/color/landscape/Mod-98.avif",
            "/images/avif/color/landscape/Mod.avif"
        ],
        portrait: [
            "/images/avif/color/portrait/Mod-101.avif",
            "/images/avif/color/portrait/Mod-108.avif",
            "/images/avif/color/portrait/Mod-109.avif",
            "/images/avif/color/portrait/Mod-11.avif",
            "/images/avif/color/portrait/Mod-110.avif",
            "/images/avif/color/portrait/Mod-111.avif",
            "/images/avif/color/portrait/Mod-112.avif",
            "/images/avif/color/portrait/Mod-113.avif",
            "/images/avif/color/portrait/Mod-114.avif",
            "/images/avif/color/portrait/Mod-115.avif",
            "/images/avif/color/portrait/Mod-116.avif",
            "/images/avif/color/portrait/Mod-117.avif",
            "/images/avif/color/portrait/Mod-118.avif",
            "/images/avif/color/portrait/Mod-119.avif",
            "/images/avif/color/portrait/Mod-12.avif",
            "/images/avif/color/portrait/Mod-121.avif",
            "/images/avif/color/portrait/Mod-122.avif",
            "/images/avif/color/portrait/Mod-123.avif",
            "/images/avif/color/portrait/Mod-124.avif",
            "/images/avif/color/portrait/Mod-125.avif",
            "/images/avif/color/portrait/Mod-126.avif",
            "/images/avif/color/portrait/Mod-128.avif",
            "/images/avif/color/portrait/Mod-129.avif",
            "/images/avif/color/portrait/Mod-13.avif",
            "/images/avif/color/portrait/Mod-130.avif",
            "/images/avif/color/portrait/Mod-131.avif",
            "/images/avif/color/portrait/Mod-132.avif",
            "/images/avif/color/portrait/Mod-133.avif",
            "/images/avif/color/portrait/Mod-134.avif",
            "/images/avif/color/portrait/Mod-136.avif",
            "/images/avif/color/portrait/Mod-137.avif",
            "/images/avif/color/portrait/Mod-138.avif",
            "/images/avif/color/portrait/Mod-139.avif",
            "/images/avif/color/portrait/Mod-14.avif",
            "/images/avif/color/portrait/Mod-140.avif",
            "/images/avif/color/portrait/Mod-151.avif",
            "/images/avif/color/portrait/Mod-152.avif",
            "/images/avif/color/portrait/Mod-154.avif",
            "/images/avif/color/portrait/Mod-161.avif",
            "/images/avif/color/portrait/Mod-162.avif",
            "/images/avif/color/portrait/Mod-163.avif",
            "/images/avif/color/portrait/Mod-164.avif",
            "/images/avif/color/portrait/Mod-165.avif",
            "/images/avif/color/portrait/Mod-167.avif",
            "/images/avif/color/portrait/Mod-168.avif",
            "/images/avif/color/portrait/Mod-169.avif",
            "/images/avif/color/portrait/Mod-17.avif",
            "/images/avif/color/portrait/Mod-170.avif",
            "/images/avif/color/portrait/Mod-172.avif",
            "/images/avif/color/portrait/Mod-174.avif",
            "/images/avif/color/portrait/Mod-18.avif",
            "/images/avif/color/portrait/Mod-2.avif",
            "/images/avif/color/portrait/Mod-22.avif",
            "/images/avif/color/portrait/Mod-23.avif",
            "/images/avif/color/portrait/Mod-24.avif",
            "/images/avif/color/portrait/Mod-25.avif",
            "/images/avif/color/portrait/Mod-26.avif",
            "/images/avif/color/portrait/Mod-27.avif",
            "/images/avif/color/portrait/Mod-28.avif",
            "/images/avif/color/portrait/Mod-30.avif",
            "/images/avif/color/portrait/Mod-31.avif",
            "/images/avif/color/portrait/Mod-34.avif",
            "/images/avif/color/portrait/Mod-37.avif",
            "/images/avif/color/portrait/Mod-39.avif",
            "/images/avif/color/portrait/Mod-4.avif",
            "/images/avif/color/portrait/Mod-40.avif",
            "/images/avif/color/portrait/Mod-41.avif",
            "/images/avif/color/portrait/Mod-44.avif",
            "/images/avif/color/portrait/Mod-45.avif",
            "/images/avif/color/portrait/Mod-46.avif",
            "/images/avif/color/portrait/Mod-48.avif",
            "/images/avif/color/portrait/Mod-49.avif",
            "/images/avif/color/portrait/Mod-50.avif",
            "/images/avif/color/portrait/Mod-54.avif",
            "/images/avif/color/portrait/Mod-55.avif",
            "/images/avif/color/portrait/Mod-58.avif",
            "/images/avif/color/portrait/Mod-59.avif",
            "/images/avif/color/portrait/Mod-60.avif",
            "/images/avif/color/portrait/Mod-61.avif",
            "/images/avif/color/portrait/Mod-63.avif",
            "/images/avif/color/portrait/Mod-64.avif",
            "/images/avif/color/portrait/Mod-65.avif",
            "/images/avif/color/portrait/Mod-67.avif",
            "/images/avif/color/portrait/Mod-69.avif",
            "/images/avif/color/portrait/Mod-71.avif",
            "/images/avif/color/portrait/Mod-72.avif",
            "/images/avif/color/portrait/Mod-73.avif",
            "/images/avif/color/portrait/Mod-74.avif",
            "/images/avif/color/portrait/Mod-75.avif",
            "/images/avif/color/portrait/Mod-76.avif",
            "/images/avif/color/portrait/Mod-8.avif",
            "/images/avif/color/portrait/Mod-86.avif",
            "/images/avif/color/portrait/Mod-87.avif",
            "/images/avif/color/portrait/Mod-90.avif",
            "/images/avif/color/portrait/Mod-95.avif",
            "/images/avif/color/portrait/Mod-96.avif",
            "/images/avif/color/portrait/Mod-99.avif"
        ]
    },
    bnw: {
        landscape: [
            "/images/avif/bnw/landscape/Mod-105.avif",
            "/images/avif/bnw/landscape/Mod-106.avif",
            "/images/avif/bnw/landscape/Mod-144.avif",
            "/images/avif/bnw/landscape/Mod-146.avif",
            "/images/avif/bnw/landscape/Mod-147.avif",
            "/images/avif/bnw/landscape/Mod-35.avif",
            "/images/avif/bnw/landscape/Mod-38.avif"
        ],
        portrait: [
            "/images/avif/bnw/portrait/Mod-104.avif",
            "/images/avif/bnw/portrait/Mod-107.avif",
            "/images/avif/bnw/portrait/Mod-145.avif",
            "/images/avif/bnw/portrait/Mod-148.avif",
            "/images/avif/bnw/portrait/Mod-155.avif",
            "/images/avif/bnw/portrait/Mod-156.avif",
            "/images/avif/bnw/portrait/Mod-157.avif",
            "/images/avif/bnw/portrait/Mod-158.avif",
            "/images/avif/bnw/portrait/Mod-159.avif",
            "/images/avif/bnw/portrait/Mod-160.avif",
            "/images/avif/bnw/portrait/Mod-19.avif",
            "/images/avif/bnw/portrait/Mod-20.avif",
            "/images/avif/bnw/portrait/Mod-21.avif",
            "/images/avif/bnw/portrait/Mod-52.avif",
            "/images/avif/bnw/portrait/Mod-53.avif",
            "/images/avif/bnw/portrait/Mod-77.avif",
            "/images/avif/bnw/portrait/Mod-78.avif",
            "/images/avif/bnw/portrait/Mod-79.avif",
            "/images/avif/bnw/portrait/Mod-80.avif",
            "/images/avif/bnw/portrait/Mod-81.avif",
            "/images/avif/bnw/portrait/Mod-88.avif",
            "/images/avif/bnw/portrait/Mod-89.avif"
        ]
    }
}

// Utility to shuffle array
export function shuffle<T>(array: T[]): T[] {
    const shuffled = [...array]
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
    }
    return shuffled
}
